# Generated by Django 5.1.3 on 2024-11-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_analysis_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='analysis_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active_member',
            field=models.BooleanField(default=False),
        ),
    ]
